--
package.path = "../?.lua;" .. package.path
require 'busted.runner'()
require 'init'
--

describe('Math Functions', function()
    describe('_:abs(value)', function()
        it('should return absolute value of `value`', function()
            assert.are.equals(_:abs(4), 4)
            assert.are.equals(_:abs(-4), 4)
        end)
    end)

    describe('_:add(...)', function()
        it('should add together all `...`', function()
            assert.are.equals(_:add(4, 6), 10)
            assert.are.equals(_:add(4, 5, 3), 12)
        end)
    end)

    describe('_:ceil(num, [precision=0])', function()
        it('rounds up `num` to `precision`', function()
            assert.are.equals(_:ceil(4.006), 5)
            assert.are.equals(_:ceil(6.004, 2), 6.01)
            assert.are.equals(_:ceil(6040, -2), 6100)
        end)
    end)

    describe('_:divide(dividend, divisor)', function()
        it('divides `dividend` by `divisor`', function()
            assert.are.equals(_:divide(6, 4), 1.5)
            assert.are.equals(_:divide(6, 3, 2), 1)
        end)
        it('attempts to `dividend` by 0, but fails', function()
            assert.has_error(function() _:divide(2, 0) end)
        end)
    end)

    describe('_:floor(num, [precision=0])', function()
        it('rounds down `num` to `precision`', function()
            assert.are.equals(_:floor(4.006), 4)
            assert.are.equals(_:floor(0.046, 2), 0.04)
            assert.are.equals(_:floor(4060, -2), 4000)
        end)
    end)

    describe('_:max(...)', function()
        it('should calculate min value of a series of numbers', function()
            assert.are.equals(_:max(4, 2, 8, 6), 8)
            assert.is_nil(_:max())
        end)
    end)

    describe('_:maxBy(tabl, [iteratee])', function()
        it('should calculate min value of series of numbers, invoking an `iteratee`', function()
            assert.are.equals(_:maxBy({4, 2, 8, 6}, function(v) return v * 2 end), 16)
        end)
    end)

    describe('_:mean(...)', function()
        it('should calculate mean of a series of numbers', function()
            assert.are.equals(_:mean(4, 2, 8, 6), 5)
        end)
    end)

    describe('_:meanBy(tabl, [iteratee])', function()
        it('should calculate mean of series of numbers, invoking an `iteratee`', function()
            assert.are.equals(_:meanBy({4, 2, 8, 6}, function(v) return v * 2 end), 10)
        end)
    end)

    describe('_:min(...)', function()
        it('should calculate min value of a series of numbers', function()
            assert.are.equals(_:min(4, 2, 8, 6), 2)
            assert.is_nil(_:min())
        end)
    end)

    describe('_:minBy(tabl, [iteratee])', function()
        it('should calculate min value of series of numbers, invoking an `iteratee`', function()
            assert.are.equals(_:minBy({4, 2, 8, 6}, function(v) return v * 2 end), 4)
        end)
    end)

    describe('_:multiply(...)', function()
        it('should multiply series of numbers', function()
            assert.are.equals(_:multiply(2, 3), 6)
            assert.are.equals(_:multiply(10, -2, 3), -60)
        end)
    end)

    describe('_:multiplyBy(tabl, [iteratee])', function()
        it('should multiply series of numbers, invoking an `iteratee`', function()
            assert.are.equals(_:multiplyBy({3, -2, 4}, function(v) return v * 2 end), -192)
        end)
    end)

    describe('_:round(num, [precision=0])', function()
        it('should round `num` to `precision`', function()
            assert.are.equals(_:round(4.006), 4)
            assert.are.equals(_:round(4.006, 2), 4.01)
            assert.are.equals(_:round(4060, -2), 4100)
        end)
    end)

    describe('_:subtract(...)', function()
        it('should subtract series of numbers', function()
            assert.are.equals(_:subtract(2, 3), -1)
            assert.are.equals(_:subtract(10, -2, 3, 0), 9)
        end)
    end)

    describe('_:subtractBy(tabl, [iteratee])', function()
        it('should subtract series of numbers, invoking an `iteratee`', function()
            assert.are.equals(_:subtractBy({3, -2, 4}, function(v) return v * 2 end), 2)
        end)
    end)

    describe('_:sum(...)', function()
        it('should sum series of numbers', function()
            assert.are.equals(_:sum(2, 3), 5)
            assert.are.equals(_:sum(2, 3, 4, 5), 14)
        end)
    end)

    describe('_:sumBy(tabl, [iteratee])', function()
        it('should sum `tabl` of numbers, invoking `iteratee`', function()
            assert.are.equals(_:sumBy({1, 2, 3}, function(v) return v * 2 end), 12)
        end)
    end)

    describe('_:toDeg(rad)', function()
        it('should convert degrees to radians', function()
            assert.are.equals(_:toDeg(math.pi / 2), 90)
            assert.are.equals(_:toDeg(math.pi / 3), 60)
        end)
    end)

    describe('_:toRad(deg)', function()
        it('should convert radians to degrees', function()
            assert.are.equals(_:toRad(30), 0.523599)
            assert.are.equals(_:toRad(180), 3.141593)
        end)
    end)
end)